"""
STATCOM and reactive power compensation sizing for 510 MW offshore wind farm.

Calculates the reactive power generated by the two 220 kV export cables, sizes the
STATCOM (±120 MVAR) and shunt reactors (3 × 80 MVAR, N+1), and validates that the
compensation scheme maintains voltage compliance.

Physics — Ferranti Effect
--------------------------
An unloaded or lightly loaded cable generates significant capacitive reactive
power due to the distributed capacitance of the XLPE insulation. This raises
the receiving-end voltage above the sending-end voltage — the Ferranti effect:

  V_receiving ≈ V_sending / cos(βL)

where β = ω√(LC) is the phase constant [rad/km] and L is cable length [km].
For a 45 km, 220 kV cable, the Ferranti rise is typically 2-5%.

Physics — Cable Reactive Power (Rule 7)
-----------------------------------------
The total capacitive reactive power generated by a cable (Rule 7: always positive):

  Q_cable = ω × C × V² × L  [VAR]

For one 220 kV, 45 km export cable:
  ω = 2π × 50 = 314.16 rad/s
  C = 190 nF/km = 190 × 10⁻⁹ F/km
  V = 220 kV = 220,000 V
  L = 45 km

  Q_cable = 314.16 × 190e-9 × (220,000)² × 45
          = 314.16 × 190e-9 × 4.84e10 × 45
          ≈ 130 MVAR (total three-phase, both ends)

Two parallel export cables → Q_total ≈ 2 × 130 = 260 MVAR.

Note: The actual Q depends on loading — the formula above is the open-circuit
charging power. Under load, the reactive power consumption of the cable reduces
the net Q. Pandapower models this accurately with the pi-model.

STATCOM vs SVC Decision
-------------------------
STATCOM (Voltage Source Converter) advantages over SVC:
  - Full Q at low voltage (important during FRT)
  - Faster response (< 1 cycle vs 2-3 cycles)
  - Smaller footprint on offshore platform
  - No harmonic filters needed (PWM switching)

Sizing (size_statcom) — design case is N-1 (one reactor out of service):
  (Q_cable − (N − 1) × Q_reactor) × (1 + 10% temperature + 5% ageing)
  = (260 − 2 × 80) × 1.15 = 115 → rounded up to ±120 MVAR
Normal operation (all 3 in): 260 − 240 = 20 MVAR, so the STATCOM idles with its
full ±120 MVAR available for voltage control and FRT support.
Shunt reactors are much cheaper per MVAR than a STATCOM, so an N+1 spare
reactor is the economical way to make the scheme N-1 secure.

References
----------
- IEC 62927: Voltage source converter (VSC) valves for STATCOM
- CIGRE TB 144: STATCOM analysis and design
- PSE IRiESP: Reactive power compensation requirements
- ENTSO-E NC RfG: Type D Q/P capability requirements

Constants (Baltic Wind Alpha)
-----------------------------
- Export cables: 2 × 220 kV, 45 km, C = 190 nF/km each
- STATCOM: ±120 MVAR at OSS 220 kV
- Shunt reactors: 3 × 80 MVAR at OSS 220 kV (N+1)
- Voltage limits: 0.95–1.05 p.u.
"""

import math

import pandapower as pp

from app.schemas.grid import STATCOMSizingResult
from app.services.p2.load_flow import V_MAX_PU, V_MIN_PU, auto_statcom_dispatch
from app.services.p2.network_model import (
    EXPORT_CABLE_1000,
    EXPORT_CABLE_LENGTH_KM,
    NUM_EXPORT_CABLES,
    NUM_SHUNT_REACTORS,
    SHUNT_REACTOR_MVAR,
    SHUNT_REACTOR_UNIT_MVAR,
    STATCOM_RATING_MVAR,
    build_network,
)

# System frequency
FREQUENCY_HZ = 50.0
OMEGA = 2.0 * math.pi * FREQUENCY_HZ  # 314.16 rad/s


def calculate_cable_reactive_power(
    c_nf_per_km: float = EXPORT_CABLE_1000.c_nf_per_km,
    voltage_kv: float = 220.0,
    length_km: float = EXPORT_CABLE_LENGTH_KM,
    num_cables: int = NUM_EXPORT_CABLES,
) -> float:
    """Calculate cable capacitive reactive power generation.

    Rule 7: Cable Q is always positive (capacitive generation).

    Q_cable = ω × C × V² × L  [MVAR]

    This is the total three-phase charging power at rated voltage.

    Parameters
    ----------
    c_nf_per_km : float
        Cable capacitance per phase [nF/km]. Default: 190 (export cable).
    voltage_kv : float
        Nominal voltage [kV]. Default: 220.
    length_km : float
        Cable length [km]. Default: 45.
    num_cables : int
        Number of parallel cables. Default: 2 (export circuits).

    Returns
    -------
    float
        Capacitive reactive power [MVAR]. Always positive (Rule 7).
    """
    c_f_per_km = c_nf_per_km * 1e-9  # nF → F
    v_v = voltage_kv * 1e3  # kV → V

    # Q = ω × C × V² × L (per phase, but C is per-phase already in pi-model)
    # Total three-phase Q = 3 × ω × C × V_phase² = ω × C × V_line²
    q_var = OMEGA * c_f_per_km * v_v**2 * length_km * num_cables
    q_mvar = q_var / 1e6

    return q_mvar  # Rule 7: always positive


def size_statcom(
    cable_q_mvar: float | None = None,
    reactor_unit_mvar: float = SHUNT_REACTOR_UNIT_MVAR,
    num_reactors: int = NUM_SHUNT_REACTORS,
    reactors_out: int = 1,
    temperature_derating: float = 0.10,
    aging_factor: float = 0.05,
) -> float:
    """Size STATCOM rating with engineering margins.

    The STATCOM must cover the reactive power left after the in-service
    reactors, plus temperature and ageing margins. The default design case is
    N-1: one reactor out of service.

    Parameters
    ----------
    cable_q_mvar : float | None
        Export cable Q [MVAR]. If None, calculated from cable parameters.
    reactor_unit_mvar : float
        Absorption of one shunt reactor [MVAR]. Default: 80.
    num_reactors : int
        Installed shunt reactors. Default: 3 (N+1).
    reactors_out : int
        Reactors out of service in the design case. Default: 1 (N-1).
    temperature_derating : float
        Temperature derating factor (e.g. 0.10 = 10%). Default: 0.10.
    aging_factor : float
        Aging derating factor (e.g. 0.05 = 5%). Default: 0.05.

    Returns
    -------
    float
        Required STATCOM rating (±) [MVAR].
    """
    if cable_q_mvar is None:
        cable_q_mvar = calculate_cable_reactive_power()

    # Net Q after the in-service reactors; abs() because too much reactor
    # makes the STATCOM generate instead of absorb — both use its rating
    in_service = max(num_reactors - reactors_out, 0)
    net_q = abs(cable_q_mvar - reactor_unit_mvar * in_service)

    # Apply margins
    derating = 1.0 + temperature_derating + aging_factor
    required_rating = net_q * derating

    # Round up to nearest 10 MVAR
    return math.ceil(required_rating / 10.0) * 10.0


def validate_compensation(
    export_length_km: float = EXPORT_CABLE_LENGTH_KM,
    grid_ssc_mva: float = 10_000.0,
) -> STATCOMSizingResult:
    """Validate reactive power compensation by comparing load flow with and without.

    Runs these load flow analyses:
    1. Without compensation (no reactor, no STATCOM) — shows Ferranti voltage rise
    2. With compensation (reactors + auto-dispatched STATCOM) — shows compliance
    3. Reactor N-1 (one reactor out) at no load and full load — the STATCOM must
       keep the voltage compliant without saturating at its rating

    Parameters
    ----------
    export_length_km : float
        Export cable length [km]. Default: 45.0.
    grid_ssc_mva : float
        Grid short-circuit power [MVA]. Default: 10,000.

    Returns
    -------
    STATCOMSizingResult
        Sizing result with cable Q, Ferranti rise, and compensation adequacy.
    """
    cable_q = calculate_cable_reactive_power(
        length_km=export_length_km,
    )

    # ── Without compensation: no reactor, no STATCOM ──────────────
    net_uncompensated = build_network(
        export_length_km=export_length_km,
        grid_ssc_mva=grid_ssc_mva,
        generation_fraction=0.0,  # No-load (worst Ferranti)
        statcom_q_mvar=0.0,
        enable_reactor=False,
    )
    pp.runpp(net_uncompensated, algorithm="nr", max_iteration=100, tolerance_mva=1e-8)

    # Get max voltage without compensation (Ferranti rise)
    if net_uncompensated.converged:
        without_v_max = float(net_uncompensated.res_bus.vm_pu.max())
        # Ferranti rise relative to 1.0 pu
        ferranti_rise = without_v_max - 1.0
    else:
        without_v_max = 0.0
        ferranti_rise = 0.0

    # ── With compensation: reactors + auto-dispatched STATCOM ─────
    compensation_adequate, _ = _run_compensated(export_length_km, grid_ssc_mva, 0.0, 0)

    # ── Reactor N-1: one reactor out, no load (worst) and full load ──
    n1_results = [
        _run_compensated(export_length_km, grid_ssc_mva, gen, reactors_out=1) for gen in (0.0, 1.0)
    ]
    n1_statcom_q = max((q for _, q in n1_results), key=abs)
    reactor_n1_secure = all(ok for ok, _ in n1_results) and abs(n1_statcom_q) < STATCOM_RATING_MVAR

    return STATCOMSizingResult(
        cable_q_mvar=round(cable_q, 1),
        reactor_q_mvar=SHUNT_REACTOR_MVAR,
        ferranti_rise_pu=round(ferranti_rise, 4),
        statcom_rating_mvar=STATCOM_RATING_MVAR,
        statcom_q_range_min_mvar=-STATCOM_RATING_MVAR,
        statcom_q_range_max_mvar=STATCOM_RATING_MVAR,
        compensation_adequate=compensation_adequate,
        without_compensation_v_max_pu=round(without_v_max, 4),
        reactor_n1_statcom_q_mvar=round(n1_statcom_q, 1),
        reactor_n1_secure=reactor_n1_secure,
    )


def _run_compensated(
    export_length_km: float,
    grid_ssc_mva: float,
    generation_fraction: float,
    reactors_out: int,
) -> tuple[bool, float]:
    """Load flow with reactors + auto-dispatched STATCOM.

    Returns
    -------
    tuple[bool, float]
        (all non-slack bus voltages within V_MIN_PU–V_MAX_PU, STATCOM Q [MVAR]).
    """
    net = build_network(
        export_length_km=export_length_km,
        grid_ssc_mva=grid_ssc_mva,
        generation_fraction=generation_fraction,
        statcom_q_mvar=0.0,
        enable_reactor=True,
    )
    net.shunt.loc[net.shunt.index[:reactors_out], "in_service"] = False
    statcom_q = auto_statcom_dispatch(net)
    if not net.converged:
        return False, statcom_q
    vm = net.res_bus.vm_pu[~net.bus["name"].str.contains("PSE")]
    return bool(vm.min() >= V_MIN_PU and vm.max() <= V_MAX_PU), statcom_q
