"""
STATCOM and reactive power compensation sizing for 510 MW offshore wind farm.

Calculates the reactive power generated by the two 220 kV export cables, sizes the
STATCOM (±120 MVAR) and shunt reactors (3 × 170 MVAR, N+1), and validates that the
compensation scheme maintains voltage compliance.

Physics — two different voltage rises
--------------------------------------
1. Ferranti effect *along* an open-ended cable:

     V_receiving ≈ V_sending / cos(βL),   β = ω√(L′C′)

   For 76.5 km of this cable βL ≈ 0.20 rad → ≈ 2 %.
2. Uncompensated charging current flowing *through* the cable, the transformers
   and the grid: 442 MVAR raise the offshore voltage by ≈ 15 % (load flow).
   This, not the Ferranti effect, is what the shunt reactors are for.

Physics — Cable Reactive Power (Rule 7)
-----------------------------------------
The total capacitive reactive power generated by a cable (Rule 7: always positive):

  Q_cable = ω × C × V² × L  [VAR]

For one 220 kV, 76.5 km export cable:
  ω = 2π × 50 = 314.16 rad/s
  C = 190 nF/km = 190 × 10⁻⁹ F/km
  V = 220 kV = 220,000 V
  L = 76.5 km

  Q_cable = 314.16 × 190e-9 × (220,000)² × 76.5
          = 314.16 × 190e-9 × 4.84e10 × 76.5
          ≈ 221 MVAR (total three-phase, both ends)

Two parallel export cables → Q_total ≈ 2 × 221 = 442 MVAR.

Note: The actual Q depends on loading — the formula above is the open-circuit
charging power. Under load, the reactive power consumption of the cable reduces
the net Q. Pandapower models this accurately with the pi-model.

STATCOM vs SVC Decision
-------------------------
STATCOM (Voltage Source Converter) advantages over SVC:
  - Full Q at low voltage (important during FRT)
  - Faster response (< 1 cycle vs 2-3 cycles)
  - Smaller footprint on offshore platform
  - No harmonic filters needed (PWM switching)

Grid-code reactive range (what actually sizes the scheme)
----------------------------------------------------------
PSE (NC RfG requirements, 18-12-2018, Art. 21(3)(c)) asks a type-D power park
module for Q/P_max from −0.35 (absorbing) to +0.40 (producing) at the
connection point for P ≥ 0.1 P_max: −178.5 / +204 MVAR for 510 MW.
``poc_q_capability`` finds what the scheme delivers at P_max: WTG reactive
capability (assumed ±0.33 p.u., cos φ = 0.95 at rated power — the V236 data
sheet is not public), STATCOM ±120 MVAR, switching the shunt reactors, and
both OLTCs regulating, with every farm bus kept within 0.90–1.10 p.u.

Sizing (size_statcom) — design case is N-1 (one reactor out of service):
  (Q_cable − (N − 1) × Q_reactor) × (1 + 10% temperature + 5% ageing)
  = (442 − 2 × 170) × 1.15 = 117 → rounded up to ±120 MVAR
Normal operation: all 3 in would over-compensate (442 − 510 = −68 MVAR, and at
full output the series I²X absorption adds to it), so the spare is kept out:
2 × 170 in, the STATCOM moves between ≈ −50 (no load) and ≈ +10 MVAR (rated)
and keeps most of its ±120 MVAR for voltage control and FRT support.
Shunt reactors are much cheaper per MVAR than a STATCOM, so an N+1 spare
reactor is the economical way to make the scheme N-1 secure.

References
----------
- IEC 62927: Voltage source converter (VSC) valves for STATCOM
- CIGRE TB 144: STATCOM analysis and design
- PSE: Wymogi ogólnego stosowania wynikające z NC RfG (18-12-2018), Art. 21(3)(b)–(c)
- ENTSO-E NC RfG (EU 2016/631) Art. 21: reactive capability of type-D PPMs

Constants (SB-510)
-----------------------------
- Export cables: 2 × 220 kV, 76.5 km, C = 190 nF/km each
- STATCOM: ±120 MVAR at OSS 220 kV
- Shunt reactors: 3 × 170 MVAR at OSS 220 kV (N+1)
- Voltage limits: 0.95–1.05 p.u.
"""

import dataclasses
import math
from functools import lru_cache

import pandapower as pp
from pandapower.control import DiscreteTapControl

from app.schemas.grid import STATCOMSizingResult
from app.services.p2.load_flow import V_MAX_PU, V_MIN_PU, auto_statcom_dispatch
from app.services.p2.network_model import (
    EXPORT_CABLE_1000,
    EXPORT_CABLE_LENGTH_KM,
    GRID_SSC_MVA,
    NUM_EXPORT_CABLES,
    NUM_SHUNT_REACTORS,
    SB510,
    SHUNT_REACTOR_UNIT_MVAR,
    FarmSpec,
    build_network,
)

# System frequency
FREQUENCY_HZ = 50.0
OMEGA = 2.0 * math.pi * FREQUENCY_HZ  # 314.16 rad/s

# PSE Art. 21(3)(c): Q/P_max range at the connection point, P ≥ 0.1 P_max
PSE_Q_PRODUCE_PU = 0.40
PSE_Q_ABSORB_PU = 0.35
WTG_Q_CAPABILITY_PU = 0.33  # ±Q/S_n at rated power (cos φ 0.95) — assumption
CAPABILITY_V_MIN_PU = 0.90
CAPABILITY_V_MAX_PU = 1.10


def ferranti_rise_pu(length_km: float = EXPORT_CABLE_LENGTH_KM) -> float:
    """Open-end voltage rise along the export cable itself: 1/cos(βL) − 1 [p.u.]."""
    cable = EXPORT_CABLE_1000
    inductance_h = cable.x_ohm_per_km / OMEGA
    beta = OMEGA * math.sqrt(inductance_h * cable.c_nf_per_km * 1e-9)
    return 1.0 / math.cos(beta * length_km) - 1.0


def calculate_cable_reactive_power(
    c_nf_per_km: float = EXPORT_CABLE_1000.c_nf_per_km,
    voltage_kv: float = 220.0,
    length_km: float = EXPORT_CABLE_LENGTH_KM,
    num_cables: int = NUM_EXPORT_CABLES,
) -> float:
    """Calculate cable capacitive reactive power generation.

    Rule 7: Cable Q is always positive (capacitive generation).

    Q_cable = ω × C × V² × L  [MVAR]

    This is the total three-phase charging power at rated voltage.

    Parameters
    ----------
    c_nf_per_km : float
        Cable capacitance per phase [nF/km]. Default: 190 (export cable).
    voltage_kv : float
        Nominal voltage [kV]. Default: 220.
    length_km : float
        Cable length [km]. Default: 45.
    num_cables : int
        Number of parallel cables. Default: 2 (export circuits).

    Returns
    -------
    float
        Capacitive reactive power [MVAR]. Always positive (Rule 7).
    """
    c_f_per_km = c_nf_per_km * 1e-9  # nF → F
    v_v = voltage_kv * 1e3  # kV → V

    # Q = ω × C × V² × L (per phase, but C is per-phase already in pi-model)
    # Total three-phase Q = 3 × ω × C × V_phase² = ω × C × V_line²
    q_var = OMEGA * c_f_per_km * v_v**2 * length_km * num_cables
    q_mvar = q_var / 1e6

    return q_mvar  # Rule 7: always positive


def size_statcom(
    cable_q_mvar: float | None = None,
    reactor_unit_mvar: float = SHUNT_REACTOR_UNIT_MVAR,
    num_reactors: int = NUM_SHUNT_REACTORS,
    reactors_out: int = 1,
    temperature_derating: float = 0.10,
    aging_factor: float = 0.05,
) -> float:
    """Size STATCOM rating with engineering margins.

    The STATCOM must cover the reactive power left after the in-service
    reactors, plus temperature and ageing margins. The default design case is
    N-1: one reactor out of service.

    Parameters
    ----------
    cable_q_mvar : float | None
        Export cable Q [MVAR]. If None, calculated from cable parameters.
    reactor_unit_mvar : float
        Absorption of one shunt reactor [MVAR]. Default: 80.
    num_reactors : int
        Installed shunt reactors. Default: 3 (N+1).
    reactors_out : int
        Reactors out of service in the design case. Default: 1 (N-1).
    temperature_derating : float
        Temperature derating factor (e.g. 0.10 = 10%). Default: 0.10.
    aging_factor : float
        Aging derating factor (e.g. 0.05 = 5%). Default: 0.05.

    Returns
    -------
    float
        Required STATCOM rating (±) [MVAR].
    """
    if cable_q_mvar is None:
        cable_q_mvar = calculate_cable_reactive_power()

    # Net Q after the in-service reactors; abs() because too much reactor
    # makes the STATCOM generate instead of absorb — both use its rating
    in_service = max(num_reactors - reactors_out, 0)
    net_q = abs(cable_q_mvar - reactor_unit_mvar * in_service)

    # Apply margins
    derating = 1.0 + temperature_derating + aging_factor
    required_rating = net_q * derating

    # Round up to nearest 10 MVAR
    return math.ceil(required_rating / 10.0) * 10.0


@lru_cache(maxsize=16)
def validate_compensation(
    export_length_km: float | None = None,
    grid_ssc_mva: float = 10_000.0,
    spec: FarmSpec = SB510,
) -> STATCOMSizingResult:
    """Validate reactive power compensation by comparing load flow with and without.

    Runs these load flow analyses:
    1. Without compensation (no reactor, no STATCOM) — shows Ferranti voltage rise
    2. With compensation (reactors + auto-dispatched STATCOM) — shows compliance
    3. Reactor N-1 (one reactor out) at no load and full load — the STATCOM must
       keep the voltage compliant without saturating at its rating

    Parameters
    ----------
    export_length_km : float | None
        Export cable length [km]; None = the spec's (SB-510: 76.5).
    grid_ssc_mva : float
        Grid short-circuit power [MVA]. Default: 10,000.
    spec : FarmSpec
        Farm design (STATCOM, reactors, export circuits). Default: SB-510.

    Returns
    -------
    STATCOMSizingResult
        Sizing result with cable Q, Ferranti rise, and compensation adequacy.
    """
    if export_length_km is None:
        export_length_km = spec.export_length_km
    cable_q = calculate_cable_reactive_power(
        length_km=export_length_km, num_cables=spec.num_export_cables
    )

    # ── Without compensation: no reactor, no STATCOM ──────────────
    net_uncompensated = build_network(
        export_length_km=export_length_km,
        grid_ssc_mva=grid_ssc_mva,
        generation_fraction=0.0,  # No-load (worst Ferranti)
        statcom_q_mvar=0.0,
        enable_reactor=False,
        spec=spec,
    )
    pp.runpp(net_uncompensated, algorithm="nr", max_iteration=100, tolerance_mva=1e-8)

    # Max voltage without compensation (charging current through the transformers)
    without_v_max = (
        float(net_uncompensated.res_bus.vm_pu.max()) if net_uncompensated.converged else 0.0
    )

    # ── With compensation: reactors + auto-dispatched STATCOM ─────
    compensation_adequate, _ = _run_compensated(export_length_km, grid_ssc_mva, 0.0, 0, spec)

    # ── Reactor N-1: one reactor out, no load (worst) and full load ──
    n1_results = [
        _run_compensated(export_length_km, grid_ssc_mva, gen, 1, spec) for gen in (0.0, 1.0)
    ]
    n1_statcom_q = max((q for _, q in n1_results), key=abs)
    reactor_n1_secure = all(ok for ok, _ in n1_results) and abs(n1_statcom_q) < spec.statcom_mvar

    q_max, q_min = poc_q_capability(export_length_km, grid_ssc_mva, spec)
    required_max = PSE_Q_PRODUCE_PU * spec.capacity_mw
    required_min = -PSE_Q_ABSORB_PU * spec.capacity_mw

    return STATCOMSizingResult(
        cable_q_mvar=round(cable_q, 1),
        reactor_q_mvar=spec.reactor_mvar,
        ferranti_rise_pu=round(ferranti_rise_pu(export_length_km), 4),
        uncompensated_rise_pu=round(without_v_max - 1.0, 4) if without_v_max else 0.0,
        statcom_rating_mvar=spec.statcom_mvar,
        statcom_q_range_min_mvar=-spec.statcom_mvar,
        statcom_q_range_max_mvar=spec.statcom_mvar,
        compensation_adequate=compensation_adequate,
        without_compensation_v_max_pu=round(without_v_max, 4),
        reactor_n1_statcom_q_mvar=round(n1_statcom_q, 1),
        reactor_n1_secure=reactor_n1_secure,
        poc_q_max_mvar=round(q_max, 1),
        poc_q_min_mvar=round(q_min, 1),
        pse_q_max_mvar=round(required_max, 1),
        pse_q_min_mvar=round(required_min, 1),
        pse_q_range_met=q_max >= required_max and q_min <= required_min,
        wtg_q_capability_mvar=round(WTG_Q_CAPABILITY_PU * spec.turbine_rated_mw, 2),
    )


def continuous_q_mvar(spec: FarmSpec = SB510) -> float:
    """Q the WTGs and the STATCOM give without switching reactors [MVAR]."""
    return WTG_Q_CAPABILITY_PU * spec.capacity_mw + spec.statcom_mvar


def _poc_q_at(
    q_inj_mvar: float, export_length_km: float, grid_ssc_mva: float, spec: FarmSpec = SB510
) -> tuple[float, bool]:
    """POC reactive power for a requested internal injection, and voltage feasibility.

    q_inj > 0 (producing): WTGs and STATCOM first, then shunt reactors are
    switched out one by one (SB-510: 170 MVAR steps). q_inj < 0: WTGs and STATCOM
    absorb with all reactors in. Both OLTCs hold their LV busbar at 0.99–1.01 p.u.
    """
    cont = continuous_q_mvar(spec)
    reactors_out = 0
    if q_inj_mvar > cont and spec.num_reactors:
        reactors_out = min(
            spec.num_reactors,
            math.ceil((q_inj_mvar - cont) / spec.reactor_unit_mvar),
        )
    q_cont = q_inj_mvar - reactors_out * spec.reactor_unit_mvar
    share = max(min(q_cont / cont, 1.0), -1.0)  # same fraction on every source

    net = build_network(
        export_length_km=export_length_km,
        grid_ssc_mva=grid_ssc_mva,
        generation_fraction=1.0,
        statcom_q_mvar=share * spec.statcom_mvar,
        spec=spec,
    )
    net.shunt.loc[net.shunt.index[:reactors_out], "in_service"] = False
    wtg = net.sgen["name"].str.startswith("WTG_")
    net.sgen.loc[wtg, "q_mvar"] = share * WTG_Q_CAPABILITY_PU * spec.turbine_rated_mw
    for idx in net.trafo.index:
        DiscreteTapControl(net, idx, vm_lower_pu=0.99, vm_upper_pu=1.01, side="lv")
    pp.runpp(net, run_control=True, max_iteration=100, tolerance_mva=1e-6)
    if not net.converged:
        return 0.0, False
    vm = net.res_bus.vm_pu[~net.bus["name"].str.contains("PSE")]
    ok = bool(vm.min() >= CAPABILITY_V_MIN_PU and vm.max() <= CAPABILITY_V_MAX_PU)
    return -float(net.res_ext_grid.q_mvar.sum()), ok  # delivered to PSE, generating +


@lru_cache(maxsize=16)
def poc_q_capability(
    export_length_km: float = EXPORT_CABLE_LENGTH_KM,
    grid_ssc_mva: float = GRID_SSC_MVA,
    spec: FarmSpec = SB510,
) -> tuple[float, float]:
    """Largest producing / absorbing Q at the PSE 400 kV POC at P_max [MVAR].

    Bisection on the internal injection; each trial is a load flow with OLTC
    control, accepted only if every farm bus stays within 0.90–1.10 p.u.
    """
    cont = continuous_q_mvar(spec)
    tops = {+1: cont + spec.reactor_mvar, -1: cont}
    result: dict[int, float] = {}
    for sign, top in tops.items():
        q_top, ok_top = _poc_q_at(sign * top, export_length_km, grid_ssc_mva, spec)
        if ok_top:
            result[sign] = q_top
            continue
        lo, hi = 0.0, top
        best, _ = _poc_q_at(0.0, export_length_km, grid_ssc_mva, spec)
        for _ in range(7):
            mid = 0.5 * (lo + hi)
            q, ok = _poc_q_at(sign * mid, export_length_km, grid_ssc_mva, spec)
            if ok:
                lo, best = mid, q
            else:
                hi = mid
        result[sign] = best
    return result[+1], result[-1]


def _run_compensated(
    export_length_km: float,
    grid_ssc_mva: float,
    generation_fraction: float,
    reactors_out: int,
    spec: FarmSpec = SB510,
) -> tuple[bool, float]:
    """Load flow with reactors + auto-dispatched STATCOM.

    Returns
    -------
    tuple[bool, float]
        (all non-slack bus voltages within V_MIN_PU–V_MAX_PU, STATCOM Q [MVAR]).
    """
    net = build_network(
        export_length_km=export_length_km,
        grid_ssc_mva=grid_ssc_mva,
        generation_fraction=generation_fraction,
        statcom_q_mvar=0.0,
        enable_reactor=True,
        spec=spec,
    )
    net.shunt.loc[net.shunt.index[:reactors_out], "in_service"] = False
    statcom_q = auto_statcom_dispatch(net)
    if not net.converged:
        return False, statcom_q
    vm = net.res_bus.vm_pu[~net.bus["name"].str.contains("PSE")]
    return bool(vm.min() >= V_MIN_PU and vm.max() <= V_MAX_PU), statcom_q


REACTOR_STEP_MVAR = 10.0
REACTOR_STEPS = 6


@lru_cache(maxsize=64)
def check_reactors(spec: FarmSpec) -> FarmSpec:
    """Raise the reactor unit until the reactor-N-1 case keeps the STATCOM off its limit.

    ``network_model.design`` sizes the reactors from the charging-power balance;
    what the STATCOM really has to absorb is set by voltage regulation at the
    OSS (dQ/dV through the export and the transformers), which the balance
    misses for short single-circuit exports. Each step is the same no-load and
    full-load load flow ``validate_compensation`` uses (one reactor out); the
    unit grows in 10 MVAR steps, at most six. SB-510 passes as designed.
    """
    for _ in range(REACTOR_STEPS):
        if not spec.num_reactors:
            return spec
        runs = [
            _run_compensated(spec.export_length_km, spec.grid_ssc_mva, g, 1, spec)
            for g in (0.0, 1.0)
        ]
        if all(ok for ok, _ in runs) and max(abs(q) for _, q in runs) < spec.statcom_mvar:
            return spec
        spec = dataclasses.replace(
            spec, reactor_unit_mvar=spec.reactor_unit_mvar + REACTOR_STEP_MVAR
        )
    return spec
