/** Turkish: Evidence page rows (src/data/evidence.json, written by backend scripts/build_evidence.py). Citations stay as written. */
export default {
  "Digital twin": "Dijital ikiz",
  "Physics-residual detector on real turbine SCADA (CARE Farm B, tuning set)":
    "Gerçek türbin SCADA'sında fizik artığı dedektörü (CARE Farm B, ayar kümesi)",
  "labelled fault and normal periods, CARE to Compare (Gück et al. 2024)":
    "etiketli arıza ve normal dönemler, CARE to Compare (Gück et al. 2024)",
  "faults detected before failure (of 6)": "arızadan önce tespit edilen arızalar (6'dan)",
  "false alarms (of 9 normal periods)": "yanlış alarmlar (9 normal dönemden)",
  "fewer than v1": "v1'den az",
  "Same detector, method frozen on Farm B, run once on Farm C (held out)":
    "Aynı dedektör, yöntem Farm B'de donduruldu, Farm C'de bir kez çalıştırıldı (ayrılmış veri)",
  "27 labelled fault periods, CARE Farm C": "27 etiketli arıza dönemi, CARE Farm C",
  "faults detected before failure": "arızadan önce tespit edilen arızalar",
  "reported as-is": "olduğu gibi raporlanır",
  "P1 — wind resource": "P1 — rüzgâr kaynağı",
  "Our TurbOPark set-up (cluster wakes) is Ørsted's model": "TurbOPark kurulumumuz (küme izleri) Ørsted'in modelidir",
  "Ørsted's TurbOPark MATLAB example 1 (4 turbines, 3 wind speeds)":
    "Ørsted'in TurbOPark MATLAB örneği 1 (4 türbin, 3 rüzgâr hızı)",
  "max relative power difference": "en büyük göreli güç farkı",
  "BPA wake model (production): row power ratios": "BPA iz modeli (üretimde): sıra güç oranları",
  "measured SCADA P_i/P_1, Horns Rev 1 + Lillgrund rows (PyWake data, MIT)":
    "ölçülen SCADA P_i/P_1, Horns Rev 1 + Lillgrund sıraları (PyWake verisi, MIT)",
  "mean RMSE over 9 rows, wind-direction averaged": "9 sıra üzerinden ortalama RMSE, rüzgâr yönüne göre ortalanmış",
  "NOJ wake model: row power ratios": "NOJ iz modeli: sıra güç oranları",
  "TurbOPark wake model: row power ratios": "TurbOPark iz modeli: sıra güç oranları",
  "P2 — HV grid": "P2 — YG şebeke",
  "Charging power of one 108 km 220 kV circuit (rule 7, capacitive Q > 0)":
    "Bir 108 km 220 kV devrenin şarj gücü (kural 7, kapasitif Q > 0)",
  "ωCL·(V_s² + V_r²)/2 − 3I²X by hand; sizing value ωCV²L = 312 Mvar":
    "elle ωCL·(V_s² + V_r²)/2 − 3I²X; boyutlandırma değeri ωCV²L = 312 Mvar",
  "Q generated by the cable (pandapower)": "kablonun ürettiği Q (pandapower)",
  "= hand formula ± 0.1 %": "= el formülü ± %0.1",
  "pandapower load flow of the 108 km export circuit (open far end)":
    "108 km iletim devresinin pandapower yük akışı (uzak uç açık)",
  "hand π-model, complex phasors (Grainger & Stevenson ch. 6)": "elle π-modeli, karmaşık fazörler (Grainger & Stevenson ch. 6)",
  "far-end voltage V_r": "uzak uç gerilimi V_r",
  "= hand π-model ± 1e-6": "= elle π-modeli ± 1e-6",
  "Ferranti rise of the open-ended export cable, 1/cos βl − 1": "Açık uçlu iletim kablosunun Ferranti yükselmesi, 1/cos βl − 1",
  "exact distributed line 1/cosh γl − 1 (with R)": "kesin dağıtılmış hat 1/cosh γl − 1 (R ile)",
  "voltage rise (our formula)": "gerilim yükselmesi (bizim formülümüz)",
  "= exact ± 1 % of the rise": "= kesin değer ± yükselmenin %1'i",
  'IEC 60909 I"k max (c = 1.1) behind a 10 GVA grid + 300 MVA transformer':
    'IEC 60909 I"k maks (c = 1.1), 10 GVA şebeke + 300 MVA transformatör arkasında',
  "IEC 60909-0:2016 hand calculation (Z_Q, K_T, κ)": "IEC 60909-0:2016 el hesabı (Z_Q, K_T, κ)",
  'I"k at 220 kV (pandapower calc_sc)': '220 kV\'ta I"k (pandapower calc_sc)',
  "= hand ± 0.01 %, i_p ± 0.1 %": "= el hesabı ± %0.01, i_p ± %0.1",
  'IEC 60909 I"k min (c = 1.0) behind a 10 GVA grid + 300 MVA transformer':
    'IEC 60909 I"k min (c = 1.0), 10 GVA şebeke + 300 MVA transformatör arkasında',
  "P2 — grid dynamics (ANDES)": "P2 — şebeke dinamiği (ANDES)",
  "Fault ride-through at 0.05 pu retained voltage: reactive current priority":
    "0.05 pu kalan gerilimde arızada devrede kalma: reaktif akım önceliği",
  "PSE fast fault current (NC RfG Art. 20(2)(b)), converter limit 1.1 pu":
    "PSE hızlı arıza akımı (NC RfG Art. 20(2)(b)), dönüştürücü sınırı 1.1 pu",
  "peak reactive current during the dip": "çukur sırasında tepe reaktif akım",
  "> 1.0 pu, stays connected": "> 1.0 pu, bağlı kalır",
  "Active power recovery after the fault is cleared": "Arıza temizlendikten sonra aktif güç toparlanması",
  "post-fault recovery to 90 % of pre-fault power (PSE, frt_simulation.py)":
    "arıza öncesi gücün %90'ına arıza sonrası toparlanma (PSE, frt_simulation.py)",
  "clearance → 90 % of pre-fault power": "temizleme → arıza öncesi gücün %90'ı",
  "LFSM-O after losing 3 GW of load: REPCA1 plant controller in ANDES":
    "3 GW yük kaybından sonra LFSM-O: ANDES'te REPCA1 santral kontrolcüsü",
  "PSE / NC RfG droop by hand: ΔP = −P_max/0.05 · (f − 50.2)/50": "PSE / NC RfG droop'u elle: ΔP = −P_max/0.05 · (f − 50.2)/50",
  "steady-state ΔP minus hand formula": "kararlı durum ΔP eksi el formülü",
  "LFSM-O response starts quickly after 50.2 Hz is crossed": "LFSM-O tepkisi 50.2 Hz aşıldıktan sonra hızla başlar",
  "NC RfG Art. 13(2) LFSM-O: an initial delay above 2 s must be justified":
    "NC RfG Art. 13(2) LFSM-O: 2 s'nin üstündeki ilk gecikme gerekçelendirilmelidir",
  "50.2 Hz crossing → 1 % output reduction": "50.2 Hz aşımı → %1 çıkış düşüşü",
  "P3 — SCADA & protection": "P3 — SCADA ve koruma",
  "Busbar fault cleared by 87B differential over GOOSE": "Bara arızası GOOSE üzerinden 87B diferansiyel ile temizlenir",
  "main-protection clearing target at 220 kV (relay + breaker)": "220 kV'ta ana koruma temizleme hedefi (röle + kesici)",
  "fault inception → arc extinction": "arıza başlangıcı → arkın sönmesi",
  "Export cable fault at 95 % of 108 km cleared by line differential 87L":
    "108 km'nin %95'indeki iletim kablosu arızası hat diferansiyeli 87L ile temizlenir",
  "PSE FRT profile allows 0 pu for 150 ms only: clear within it": "PSE FRT profili yalnızca 150 ms 0 pu'ya izin verir: bunun içinde temizle",
  "main protection clearance incl. breaker": "kesici dahil ana koruma temizlemesi",
  "The SCADA fault scenario uses the grid model's fault current": "SCADA arıza senaryosu şebeke modelinin arıza akımını kullanır",
  'IEC 60909 I"k at the OSS 220 kV busbar (pandapower, P2)': 'OSS 220 kV barasında IEC 60909 I"k (pandapower, P2)',
  "busbar fault current": "bara arıza akımı",
  "GOOSE trip transfer time in the busbar-fault sequence (fixed teaching value)":
    "Bara arızası dizisinde GOOSE açma aktarım süresi (sabit öğretim değeri)",
  "IEC 61850-5 transfer time class for trips, ≤ 3 ms": "açmalar için IEC 61850-5 aktarım süresi sınıfı, ≤ 3 ms",
  "publisher → subscriber transfer time": "yayımcı → abone aktarım süresi",
  "Overcurrent relay curve, standard inverse, 10 × pickup, TMS 1": "Aşırı akım röle eğrisi, standart ters, 10 × açma eşiği, TMS 1",
  "IEC 60255-151 formula t = 0.14 / (M^0.02 − 1) = 2.97 s": "IEC 60255-151 formülü t = 0.14 / (M^0.02 − 1) = 2.97 s",
  "operating time": "çalışma süresi",
  "66 kV feeder vs incomer overcurrent grading at the IEC 60909 fault current":
    "IEC 60909 arıza akımında 66 kV fider ile giriş aşırı akım kademelendirmesi",
  "grading margin practice (≥ 300 ms: breaker + relay overshoot + safety)":
    "kademelendirme payı uygulaması (≥ 300 ms: kesici + röle aşımı + güvenlik)",
  "time margin, evaluated on both curves": "zaman payı, iki eğride de değerlendirilir",
  "P4 — forecasting": "P4 — tahmin",
  "Day-ahead forecast: Energinet (TSO)": "Gün öncesi tahmin: Energinet (TSO)",
  "16731 measured DK2 hours (Energinet)": "16731 ölçülmüş DK2 saati (Energinet)",
  reference: "referans",
  "% of capacity": "kapasitenin %'si",
  "XGBoost P10–P90 band (conformalised) is calibrated": "XGBoost P10–P90 bandı (konformal) kalibre",
  "share of measured hours inside P10–P90": "P10–P90 içindeki ölçülmüş saatlerin payı",
  "75–90 % (ideal 80 %)": "%75–90 (ideal %80)",
  "Day-ahead forecast: XGBoost": "Gün öncesi tahmin: XGBoost",
  "CRPS skill vs climatology": "klimatolojiye karşı CRPS becerisi",
  "10–20 % (Giebel 2011); < TSO": "%10–20 (Giebel 2011); < TSO",
  "MSE skill vs 24 h persistence": "24 sa kalıcılığa karşı MSE becerisi",
  "Also checked on every run: every SB-510 number quoted in lessons, panels and tours against the backend (tests/constants/plantFacts.test.ts), and weekly every cited DOI and link. The ANDES rows run on Linux only (CI and the backend Docker image); the GOOSE transfer time is a fixed teaching value, shown against its limit.":
    "Her çalıştırmada ayrıca kontrol edilir: derslerde, panellerde ve turlarda alıntılanan her SB-510 sayısı arka uca karşı (tests/constants/plantFacts.test.ts), haftalık olarak da alıntılanan her DOI ve bağlantı. ANDES satırları yalnızca Linux'ta çalışır (CI ve arka uç Docker imajı); GOOSE aktarım süresi sınırına karşı gösterilen sabit bir öğretim değeridir.",
} satisfies Record<string, string>;
