import type { EducationContent } from "../../../types/education";

export const farmLayoutMapEducation: EducationContent = {
  id: "p1.farm-layout-map",
  title: "Farm Layout Map",
  subtitle: "Visualising turbines, cables, and wakes",
  discipline: "Civil",

  overview:
    "The layout map is the canonical engineering view of the farm: turbine positions, the OSS, the export-cable corridor, " +
    "intra-array string topology, and an overlaid wake field at the prevailing wind direction. Engineers use it to spot " +
    "obvious problems — turbines too close, exposed cable spans, asymmetric wake shadowing — before running expensive " +
    "AEP simulations.",

  simpleExplanation:
    "It's a map of the wind farm. Each dot is a turbine. The lines are the underwater cables that connect them to the " +
    "platform in the middle. The coloured background shows where wakes (slow patches of air) form when the wind blows " +
    "from one direction. Red patches mean lost energy.",

  technicalExplanation:
    "Turbine coordinates are stored in WGS84 lat/long and projected to UTM for display. Cable strings are routed via a " +
    "minimum-spanning-tree heuristic with capacity constraints (each 66 kV string carries ≤ 6 V236s ≈ 90 MW). The wake " +
    "overlay is generated by PyWake's Bastankhah/Niayifar model at the dominant wind direction, sampled on a 50 m grid. " +
    "The map is also the input to the layout optimiser, which can drag turbines within an exclusion-aware boundary.",

  standards: [
    {
      label: "IEC 61400-1 — Wind farm site classification",
      type: "standard",
      url: "https://en.wikipedia.org/wiki/IEC_61400",
    },
    {
      label: "DNV-RP-J103 — Energy yield assessment",
      type: "standard",
    },
    {
      label: "ISO 19111 — Geographic information referencing by coordinates",
      type: "standard",
      url: "https://en.wikipedia.org/wiki/ISO_19111",
    },
  ],

  formulas: [
    {
      expression: "(x_UTM, y_UTM) = WGS84_to_UTM(lat, lon, zone)",
      variables: [
        { symbol: "lat, lon", name: "WGS84 coordinates", unit: "deg" },
        { symbol: "x_UTM, y_UTM", name: "Projected easting / northing", unit: "m" },
      ],
      explanation:
        "The Polish Baltic sits in UTM zone 33N or 34N. Projection is essential for any distance computation — never compute " +
        "wake distances directly from lat/lon.",
    },
  ],

  workedExamples: [
    {
      title: "String capacity check",
      scenario:
        "34 × V236 (15.0 MW) on 66 kV array cables, max practical string ampacity 645 A.",
      steps: [
        "S_string_max = √3 · 66 kV · 645 A ≈ 73.7 MVA",
        "At 0.95 pf → P_string_max ≈ 70 MW",
        "Turbines per string = floor(70 / 15.0) = 4 per string",
        "Strings required = ceil(34 / 4) = 9 strings",
      ],
      result:
        "9 strings × 4-5 turbines each, all converging on the OSS. Higher-rated 66 kV cables (1,000 mm² Cu) can extend to " +
        "5 turbines per string and reduce string count to 7, saving cable but increasing single-fault exposure.",
    },
  ],

  realWorldCases: [
    {
      title: "Greater Gabbard — visible cable congestion",
      description:
        "Public layout charts of Greater Gabbard (UK, 504 MW, 140 turbines) show clearly the 'spine' of high-current cables " +
        "approaching the OSS. Operators replanned spare-capacity routing after a 2018 cable fault took out 90 MW for six weeks.",
      takeaway:
        "Map redundancy as much as you map turbines. The cable diagram is the single point of failure overview every chief " +
        "engineer asks for first.",
    },
  ],

  furtherReading: [
    {
      label: "EMODnet Human Activities — European offshore wind farm dataset",
      type: "website",
      url: "https://emodnet.ec.europa.eu/en/human-activities",
    },
    {
      label: "4C Offshore — Global Offshore Wind Map",
      type: "website",
      url: "https://map.4coffshore.com/offshorewind/",
    },
  ],

  codeReferences: [
    {
      file: "backend/app/services/p1/farm_layout.py",
      description: "Coordinate projection and string routing helpers for the M04 layout map.",
    },
  ],

  relatedLessons: ["lesson-005", "lesson-006"],
};
