"""P3c: alarm (ISA-18.2) and SOE event tables — models existed but were never migrated

Revision ID: 9bf504953129
Revises: a8b9c0d1e2f3
Create Date: 2026-10-05 07:42:54.739439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9bf504953129"
down_revision: Union[str, Sequence[str], None] = "a8b9c0d1e2f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarm",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "tag",
            sa.String(length=100),
            nullable=False,
            comment="Alarm tag name, e.g. 'BAY01_CB_OPEN_UNEXPECTED'",
        ),
        sa.Column(
            "display_name",
            sa.String(length=200),
            nullable=False,
            comment="Human-readable alarm name shown in SCADA",
        ),
        sa.Column(
            "priority",
            sa.String(length=10),
            nullable=False,
            comment="EEMUA 191 priority: CRITICAL / HIGH / MEDIUM / LOW / ADVISORY",
        ),
        sa.Column(
            "source_device",
            sa.String(length=100),
            nullable=False,
            comment="Originating device, e.g. 'BAY-OSS-66-01'",
        ),
        sa.Column(
            "state",
            sa.String(length=20),
            nullable=False,
            comment="Current alarm state: NORMAL / ACTIVE / ACKNOWLEDGED / SUPPRESSED",
        ),
        sa.Column(
            "cause",
            sa.Text(),
            nullable=False,
            comment="EEMUA 191 §4.2: documented cause of this alarm",
        ),
        sa.Column(
            "consequence",
            sa.Text(),
            nullable=False,
            comment="EEMUA 191 §4.2: consequence of non-response",
        ),
        sa.Column(
            "operator_action",
            sa.Text(),
            nullable=False,
            comment="EEMUA 191 §4.2: required operator response",
        ),
        sa.Column(
            "shelved",
            sa.Boolean(),
            nullable=False,
            comment="True if alarm is temporarily shelved by operator",
        ),
        sa.Column(
            "shelved_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC time when shelve expires (auto-unshelves after this)",
        ),
        sa.Column(
            "shelve_reason", sa.Text(), nullable=False, comment="Operator reason for shelving"
        ),
        sa.Column(
            "shelved_by",
            sa.String(length=100),
            nullable=True,
            comment="Operator who shelved the alarm",
        ),
        sa.Column(
            "rationalization_status",
            sa.String(length=20),
            nullable=False,
            comment="RATIONALIZED / PENDING / NEEDS_UPDATE / SUPPRESSED",
        ),
        sa.Column(
            "chattering_count",
            sa.Integer(),
            nullable=False,
            comment="ON/OFF transitions in last 10 minutes — chattering if > 3",
        ),
        sa.Column(
            "flood_suppressed",
            sa.Boolean(),
            nullable=False,
            comment="True if suppressed during an alarm flood event",
        ),
        sa.Column(
            "ack_by", sa.String(length=100), nullable=True, comment="Last operator to acknowledge"
        ),
        sa.Column(
            "ack_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC time of last acknowledgement",
        ),
        sa.Column(
            "activated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC time the alarm entered ACTIVE state",
        ),
        sa.Column(
            "cleared_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC time the alarm returned to NORMAL",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    op.create_table(
        "alarm_event",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="Sequential event ID"
        ),
        sa.Column(
            "timestamp_utc",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC event timestamp (TimescaleDB partition key)",
        ),
        sa.Column(
            "alarm_tag",
            sa.String(length=100),
            nullable=False,
            comment="Alarm tag this event belongs to",
        ),
        sa.Column(
            "transition",
            sa.String(length=30),
            nullable=False,
            comment="State transition: NORMAL_TO_ACTIVE / ACTIVE_TO_ACK / ACTIVE_TO_NORMAL / ACK_TO_NORMAL / SHELVED / UNSHELVED",
        ),
        sa.Column(
            "operator_id",
            sa.String(length=100),
            nullable=True,
            comment="Operator who performed the action (None for automatic transitions)",
        ),
        sa.Column(
            "priority",
            sa.String(length=10),
            nullable=False,
            comment="Alarm priority at time of event",
        ),
        sa.Column("source_device", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alarm_event_alarm_tag"), "alarm_event", ["alarm_tag"], unique=False)
    op.create_index(
        op.f("ix_alarm_event_timestamp_utc"), "alarm_event", ["timestamp_utc"], unique=False
    )
    op.create_table(
        "alarm_flood_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "start_utc",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC time the flood began",
        ),
        sa.Column(
            "end_utc",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC time the flood ended (None if still active)",
        ),
        sa.Column(
            "alarm_count",
            sa.Integer(),
            nullable=False,
            comment="Total alarms activated during the flood",
        ),
        sa.Column(
            "peak_rate_per_minute",
            sa.Float(),
            nullable=False,
            comment="Maximum observed alarm rate [alarms/minute] during flood",
        ),
        sa.Column(
            "suppressed_alarms",
            sa.Integer(),
            nullable=False,
            comment="Number of low-priority alarms auto-suppressed during flood",
        ),
        sa.Column(
            "resolved",
            sa.Boolean(),
            nullable=False,
            comment="True if alarm rate has returned below flood threshold",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_alarm_flood_event_start_utc"), "alarm_flood_event", ["start_utc"], unique=False
    )
    op.create_table(
        "soe_event",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="BIGSERIAL — sequential event ID for strict ordering",
        ),
        sa.Column(
            "timestamp_utc",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="UTC event timestamp — microsecond precision (TimescaleDB partition key)",
        ),
        sa.Column(
            "event_type",
            sa.String(length=30),
            nullable=False,
            comment="PROTECTION_TRIP / CB_OPERATION / ALARM_RAISED / ALARM_CLEARED / ALARM_ACKED / OPERATOR_COMMAND / INTERLOCK_BLOCK / STATE_CHANGE / COMMS_LOSS / COMMS_RESTORE",
        ),
        sa.Column(
            "source_device",
            sa.String(length=100),
            nullable=False,
            comment="Originating device/bay, e.g. 'OSS_66kV_Bay01_CB' or 'WTG-05'",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=False,
            comment="Human-readable event description for SOE report",
        ),
        sa.Column(
            "value_before",
            sa.String(length=50),
            nullable=True,
            comment="State or measurement value before the event",
        ),
        sa.Column(
            "value_after",
            sa.String(length=50),
            nullable=True,
            comment="State or measurement value after the event",
        ),
        sa.Column(
            "operator_id",
            sa.String(length=100),
            nullable=True,
            comment="Operator identifier for commanded events (None for automatic events)",
        ),
        sa.Column(
            "severity",
            sa.String(length=10),
            nullable=False,
            comment="Severity: CRITICAL / HIGH / MEDIUM / LOW / INFO",
        ),
        sa.Column(
            "acknowledged",
            sa.Boolean(),
            nullable=False,
            comment="True once an operator has acknowledged this event",
        ),
        sa.Column(
            "ack_by", sa.String(length=100), nullable=True, comment="Operator who acknowledged"
        ),
        sa.Column(
            "ack_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="UTC time of acknowledgement",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_soe_event_event_type"), "soe_event", ["event_type"], unique=False)
    op.create_index(
        op.f("ix_soe_event_source_device"), "soe_event", ["source_device"], unique=False
    )
    op.create_index(
        op.f("ix_soe_event_timestamp_utc"), "soe_event", ["timestamp_utc"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_soe_event_timestamp_utc"), table_name="soe_event")
    op.drop_index(op.f("ix_soe_event_source_device"), table_name="soe_event")
    op.drop_index(op.f("ix_soe_event_event_type"), table_name="soe_event")
    op.drop_table("soe_event")
    op.drop_index(op.f("ix_alarm_flood_event_start_utc"), table_name="alarm_flood_event")
    op.drop_table("alarm_flood_event")
    op.drop_index(op.f("ix_alarm_event_timestamp_utc"), table_name="alarm_event")
    op.drop_index(op.f("ix_alarm_event_alarm_tag"), table_name="alarm_event")
    op.drop_table("alarm_event")
    op.drop_table("alarm")
    # ### end Alembic commands ###
