/**
 * Evidence page — route /evidence.
 *
 * What the platform's models are validated against, with the measured value and the test
 * that checks it. The rows come from src/data/evidence.json, written by the backend
 * validation tests (backend/scripts/build_evidence.py); every test run compares its value
 * with this file, so the page cannot drift from the code.
 */

import evidence from "../data/evidence.json";
import { PageHeader } from "../components/layout/PageHeader";

export interface EvidenceItem {
  id: string;
  area: string;
  claim: string;
  against: string;
  metric: string;
  value: number;
  unit: string;
  limit: string;
  test: string;
}

const ITEMS = evidence.items as EvidenceItem[];
const REPO = "https://github.com/polat-mustafa/baltic-wind-control-system/blob/main/";

/** Four significant figures, no trailing zeros: 1.043, 318.8, 0.0833. */
function fmt(v: number): string {
  return String(Number(v.toPrecision(4)));
}

export default function EvidencePage() {
  const areas = [...new Set(ITEMS.map((i) => i.area))];
  return (
    <div className="space-y-5">
      <PageHeader
        title="Evidence"
        description="What each model is checked against — measured data, independent hand calculations or the reference implementation — with the value it reaches and the test that fails if it gets worse."
        meta={`${ITEMS.length} checks · generated by the backend test suite (scripts/build_evidence.py)`}
      />
      {areas.map((area) => (
        <section key={area} className="overflow-x-auto rounded-lg border border-border-primary bg-bg-secondary p-4">
          <h2 className="mb-2 text-base font-semibold text-text-primary">{area}</h2>
          <table className="w-full min-w-[760px] text-sm">
            <thead className="text-left text-xs text-text-muted">
              <tr>
                <th className="py-1 pr-3 font-medium">Claim</th>
                <th className="py-1 pr-3 font-medium">Validated against</th>
                <th className="py-1 pr-3 font-medium">Metric</th>
                <th className="py-1 pr-3 text-right font-medium">Value</th>
                <th className="py-1 pr-3 font-medium">Acceptance</th>
                <th className="py-1 font-medium">Test</th>
              </tr>
            </thead>
            <tbody className="align-top text-text-primary">
              {ITEMS.filter((i) => i.area === area).map((i) => (
                <tr key={i.id} className="border-t border-border-primary">
                  <td className="py-1.5 pr-3">{i.claim}</td>
                  <td className="py-1.5 pr-3 text-text-secondary">{i.against}</td>
                  <td className="py-1.5 pr-3 text-text-secondary">{i.metric}</td>
                  <td className="whitespace-nowrap py-1.5 pr-3 text-right font-mono tabular-nums">
                    {fmt(i.value)} {i.unit !== "−" && <span className="text-text-muted">{i.unit}</span>}
                  </td>
                  <td className="py-1.5 pr-3 font-mono text-xs text-text-secondary">{i.limit}</td>
                  <td translate="no" className="py-1.5 font-mono text-xs">
                    <a href={REPO + i.test} target="_blank" rel="noreferrer" className="text-accent hover:underline">
                      {i.test.split("/").pop()}
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>
      ))}
      <p className="text-xs text-text-muted">
        Also checked on every run: every SB-510 number quoted in lessons, panels and tours against the backend
        (tests/constants/plantFacts.test.ts), and weekly every cited DOI and link. The ANDES rows run on Linux only
        (CI and the backend Docker image); the GOOSE transfer time is a fixed teaching value, shown against its limit.
      </p>
    </div>
  );
}
